# Generated by Django 3.2 on 2023-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='title',
            field=models.CharField(default='profile', max_length=100),
        ),
    ]
