# Generated by Django 3.2 on 2023-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='投稿時間'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他'), ('system', 'システム'), ('web', 'ウェブ'), ('infrastructure', 'インフラ'), ('upstreamprocess', '上流工程'), ('programminglanguage', 'プログラミング言語'), ('PCrelated', 'PC関連'), ('game', 'ゲーム開発'), ('design', 'デザイン開発'), ('foreignlanguage', '外国語')], max_length=100, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(verbose_name='本の説明'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='本のタイトル'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='レビュー内容'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, verbose_name='レビュータイトル'),
        ),
    ]
