# Generated by Django 3.2 on 2023-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20230531_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他'), ('system', 'システム'), ('web', 'ウェブ'), ('infrastructure', 'インフラ'), ('upstreamprocess', '上流工程'), ('プログラミング言語', 'プログラミング言語'), ('PCrelated', 'PC関連'), ('game', 'ゲーム開発'), ('design', 'デザイン開発'), ('foreignlanguage', '外国語')], max_length=100, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateField(blank=True, default='2023-5-31', null=True, verbose_name='投稿時間'),
        ),
    ]
