# Generated by Django 3.2 on 2023-05-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20230531_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ビジネス', 'ビジネス'), ('生活', '生活'), ('その他', 'その他'), ('システム', 'システム'), ('ウェブ', 'ウェブ'), ('インフラ', 'インフラ'), ('上流工程', '上流工程'), ('プログラミング言語', 'プログラミング言語'), ('PC関連', 'PC関連'), ('ゲーム開発', 'ゲーム開発'), ('デザイン開発', 'デザイン開発'), ('外国語', '外国語')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
